sudo: required
services:
    - docker

before_install:
    - docker build -r raghavendranataraj/website -f Dockerfile.dev .

script:
    - docker run raghavendranataraj/website npm run test -- --coverage
